# Config package
from config.config import *

__all__ = [
    'WINDOW_WIDTH', 'WINDOW_HEIGHT', 'WINDOW_TITLE',
    'ANIMATION_FRAME_INTERVAL', 'ANIMATION_SCALE',
    'IDLE_DURATION_MIN', 'IDLE_DURATION_MAX',
    'WALK_DURATION_MIN', 'WALK_DURATION_MAX', 'WALK_SPEED',
    'AI_ENABLED', 'AI_TYPE', 'AI_API_KEY', 'AI_MODEL',
    'OLLAMA_URL', 'OLLAMA_MODEL',
    'BASE_DIR', 'ASSETS_DIR', 'SPRITES_DIR',
    'DEBUG_MODE', 'LOG_LEVEL'
]
